name: tg-prog-foundation-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - tzdata
  - pip:
      - python-telegram-bot[job-queue,rate-limiter]>=21.6,<22
      - python-dotenv>=1.0,<2
